### ISSUE TITLE
Reusing the same FetchImage with multiple URLs

### ISSUE THREAD

**Issue by kaishin** [kean/FetchImage#11]
I have a use case where I would appreciate some input. At this point it's not clear to me if this is a use case that FetchImage is designed for or not.

Basically I have a view that hosts a remote image which represents the current playing track. When the track changes, I need to update the image. 

```swift
struct Player: View {
  var currentUrl: URL
  
  var body: some View {
    CoverImage(url)
  }
}

struct CoverImage: View {
  @StateObject var remoteImage: FetchImage

  public init(_ url: URL) {
    self._remoteImage = StateObject(wrappedValue: .init(url: url))
  }

  var body: some View {
    remoteImage.view
    .onAppear {
      remoteImage.priority = .normal
      guard remoteImage.error == nil else { return }
      remoteImage.fetch()
    }
  }
}
```

The problem I am running into with this setup is that the image _doesn't change_ even when `currentUrl` changes. I tried a couple of things but it's not yielding the desired results.

Are there any easy workarounds or should reconsider using FetchImage for this use case?

**Comment by kaishin** [comment]
It's also worth noting that `onAppear` is not subsequently called in this setup. The player remains visible in the UI even when the track changes.

**Comment by kean** [comment]
> self._remoteImage = StateObject(wrappedValue: .init(url: url))

This isn't going to work because `StateObject` is tied to the view identity.

The straightforward way to do that would be to allow user to change `FetchImage` url, similar to what was suggested by in https://github.com/kean/FetchImage/issues/7. I convinced myself that this change was unnecessary complication, but it looks like it's not.

Another option would be to change `StateObject` to `ObservedObject` and inject `FetchImage`.

```swift
struct ContainerView: View {
    @StateObject var model = ContainerViewModel()
}

struct ContainerViewModel {
    @Published var fetchImage: FetchImage
}

struct CoverImage: View {
    @ObservedObject var fetchImage: FetchImage
}
```

Actually, there is probably a cleaner way. So the instance wrapped into `StateObject` can't change. But it's content can.

```swift
struct CoverImage: View {
    @StateObject var model: CoverImageViewModel
}

final class CoverImageViewModel: ObservableObject {
    @Published private(set) var image: FetchImage

    func loadImage(url: URL) {
        image = FetchImage(url: url)
    }
}
```

I haven't tried it, but I'm pretty sure this should work.

**Comment by kaishin** [comment]
Thanks for the reply @kean! I tried with `ObservedObject` but without a wrapper model which didn't work. This should work for now, albeit a bit unintuitive.

**Comment by kean** [comment]
@kaishin [FetchImage 0.4.0](https://github.com/kean/FetchImage/releases/tag/0.4.0) now has first-class support for `@StateObject`:

```swift
struct ImageView: View {
    let url: URL

    @StateObject private var image = FetchImage()

    var body: some View {
        ZStack {
            Rectangle().fill(Color.gray)
            image.view?
                .resizable()
                .aspectRatio(contentMode: .fill)
                .clipped()
        }
        .onAppear { image.load(url) }
        .onDisappear(perform: image.reset)
    }
}
```

**Comment by kaishin** [comment]
This is a really nice quality of life improvement. Thanks!

**Comment by VFUC** [comment]
Hey @kaishin , I'm running into a similar issue, though the approach from kean's last comment still behaves as you described initially on my end (image is not loaded if URL changes, since onAppear is not called again). Did you wrap the StateObject again or what was your approach?
Would appreciate any pointers (and thanks for all the work on FetchImage and Nuke, @kean ❤️ )

**Comment by kean** [comment]
Hey, @VFUC. One option is to add `.id(url)` to the image view. This will ensure that `onAppear` is called when the URL changes. From the SwiftUI perspective, one view will get removed, and another one added.

**Comment by VFUC** [comment]
Hey @kean, thanks a lot! That's a fairly clean solution I think :)
